add merge validations

diff --git a/.github/workflows/main_espaza.yml b/.github/workflows/main_espaza.yml
--- a/.github/workflows/main_espaza.yml
+++ b/.github/workflows/main_espaza.yml
@@ -4,7 +4,7 @@
 name: Build and deploy Node.js app to Azure Web App - espaza
 
 on:
-  push:
+  pull_request:
     branches:
       - main
   workflow_dispatch:
@@ -16,6 +16,15 @@ env:
   CALLBACK_URL: 'https://espaza.azurewebsites.net/auth/google/callback'
 
 jobs:
+  check_branch:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check branch
+        if: github.base_ref == 'main' && github.head_ref != 'dev'
+        run: |
+          echo "ERROR: You can only merge to main from dev."
+          exit 1
+
   build:
     runs-on: ubuntu-latest
 
diff --git a/.github/workflows/node.yml b/.github/workflows/node.yml
--- a/.github/workflows/node.yml
+++ b/.github/workflows/node.yml
@@ -4,8 +4,10 @@
 name: Node.js CI
 
 on:
-  push:
-    branches: [ "dev" ]
+  pull_request:
+    branches:
+      - dev
+  workflow_dispatch:
 
 env:
   SECRET_KEY: 'test-key'
@@ -14,8 +16,16 @@ env:
   CALLBACK_URL: 'https://espaza.azurewebsites.net/auth/google/callback'
 
 jobs:
-  build:
+  check_branch:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check branch
+        if: github.base_ref == 'dev' && startsWith(github.head_ref, 'dev-')
+        run: |
+          echo "ERROR: You can only merge to dev from dev-* branches."
+          exit 1
 
+  build:
     runs-on: ubuntu-latest
 
     strategy:
